# Generated by Django 5.2.10 on 2026-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapist',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
