# Generated by Django 5.2.10 on 2026-01-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_physiotherapist_bio_physiotherapist_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='physiotherapists/'),
        ),
    ]
