# Generated by Django 5.2.10 on 2026-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_physiotherapist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapist',
            name='photo_static_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
