# Generated by Django 5.2.10 on 2026-03-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_physiotherapist_photo_static_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapist',
            name='last_generated_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
