# Generated by Django 5.2.10 on 2026-01-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.physiotherapist')),
            ],
        ),
    ]
