# Generated by Django 5.2.10 on 2026-01-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0002_blockedslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='physiotherapist',
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.physiotherapist')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('physiotherapist', 'date', 'start_time')},
            },
        ),
        migrations.DeleteModel(
            name='BlockedSlot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
