# Generated by Django 5.2.10 on 2026-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_client_remove_booking_physiotherapist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='client_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
    ]
