# Generated by Django 5.2.10 on 2026-01-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bookingslot_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='physio_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
